# Generated by Django 3.2.3 on 2021-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0003_auto_20210610_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencista',
            name='apellido',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='conferencista',
            name='experiencia',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='conferencista',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
