# Generated by Django 3.2.3 on 2021-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0004_auto_20210610_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencista',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='conferencista',
            name='experiencia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conferencista',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
