# Generated by Django 3.2.3 on 2021-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0005_auto_20210610_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencista',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
